table fiberhmm_footprint_model
"FiberHMM footprint population model and data-derived TF-binding hypotheses"
    (
    string chrom;        "Reference chromosome / contig"
    uint chromStart;     "Consensus family start (0-based)"
    uint chromEnd;       "Consensus family end (exclusive)"
    string name;         "Stable TF geometry-family site ID"
    uint score;          "Population support (unique molecules), capped at 1000"
    char[1] strand;      "Unstranded consensus model (.)"
    string locusId;      "Stable parent binding-locus ID"
    uint familyIndex;    "Deterministic display ordinal within the parent locus"
    uint locusSummit;    "Smoothed center-density summit of the parent locus"
    uint summit;         "Center-density summit of this geometry family"
    uint assignedCallCount; "Number of source calls assigned to this family"
    uint geometryCallCount; "Number of eligible calls used to learn geometry"
    uint clusterSupportMolecules; "Unique molecules supporting learned geometry"
    uint nFullyMapped;   "Molecules fully mapping the complete family interval"
    uint nTf;            "Fully mapped molecules with an assigned TF call"
    uint nMsp;           "Fully mapped molecules whose MSP contains the family"
    uint nTfMsp;         "Molecules with both an assigned TF and containing MSP"
    uint nTfNoMsp;       "Molecules with TF and no containing MSP"
    uint nNoTfMsp;       "Molecules with containing MSP and no TF"
    uint nNoTfNoMsp;     "Molecules with neither TF nor containing MSP"
    float occupancyOverall; "nTf / nFullyMapped, or -1 when unavailable"
    float occupancyGivenMsp; "nTfMsp / nMsp, or -1 when unavailable"
    float startMad;      "Median absolute deviation of learned starts"
    float endMad;        "Median absolute deviation of learned ends"
    uint geometryReady;  "1 when geometry support reaches the reporting threshold"
    uint populationReady; "1 when TF-supporting population reaches the reporting threshold"
    )
